test:
  host: localhost
  adapter: mysql2
  database: code_grader_test
  pool: 5
  username: root
  password:

development:
  host: localhost
  adapter: mysql2
  database: code_grader_dev
  pool: 5
  username: root
  password: 

sandbox:
  host: localhost
  adapter: mysql2
  database: code_grader_sandbox
  pool: 5
  username: root
  password:

production:
  host: localhost
  adapter: mysql2
  database: code_grader_prod
  pool: 5
  username: root
  password:
